server:
  port: 8081

logging:
  level:
    org.springframework.data.redis: DEBUG
    io.lettuce: DEBUG

spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create #ddl 생성을 위해 일단 create로 설정
    open-in-view: false
  jackson:
    property-naming-strategy: SNAKE_CASE
    time-zone: Asia/Seoul
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}