server:
  port: 8090

spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/bootex
    username: testuser
    password: test1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect  # Dialect 명시 (안전장치)
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

  thymeleaf:
    cache: false

logging:
  level:
    org:
      springframework:
        security:
          web: trace
      zerock: DEBUG
